version: '3.8'

services:
  fixer-provider:
    build:
      context: ./fixer-provider
    ports:
      - "8085:8085"

  rabbitmq:
    image: rabbitmq:3.13.6-management
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ message broker port
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 171717
      MYSQL_DATABASE: gateway
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  mysql-service:
    build:
      context: ./mysql-service
    depends_on:
      - rabbitmq
      - mysql
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gateway
    ports:
      - "8082:8082"

  gateway-service:
    build:
      context: ./gateway-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_HOST: rabbitmq
      FIXER_API_URL: http://fixer-provider:8085/fixer/api
      MYSQL_API_URL: http://mysql-service:8082/rates
    ports:
      - "8081:8081"

volumes:
  db_data:
    driver: local
  rabbitmq_data:
  rabbitmq_log: